### ISSUE TITLE
macOS Catalina menubar unresponsive on cold start

### ISSUE THREAD

**Issue by rudolfs** [bryphe/revery-quick-start#47] opened 2019-10-18 13:00 UTC
When starting the app via `esy run` the macOS menubar is unresponsive. Clicking on `App`, `Window` or even the Apple icon doesn't open the dropdown.

The issue goes away once I tab to another app and tab back.
[bug.mov.zip](https://github.com/revery-ui/revery-quick-start/files/3743948/bug.mov.zip)

**Comment by rudolfs** [comment] 2019-10-24 19:59
This only seems to happen when running the app via `esy run`. When the app is packaged with `revery-packager` the menubar works as expected.

**Comment by glennsl** [comment] 2020-03-15 11:08
Thanks for reporting @rudolfs, and sorry for the late response. That's definitely an interesting issue.

I've just updated to the latest Revery, which has changed significantly since this. Could you confirm that this is still an issue, and if possible test with Revery directly as well?

**Comment by rudolfs** [comment] 2020-03-17 21:16
Hey @glennsl, thanks for the reply & no worries.

I tried to build the latest version of this repo from scratch, but bumped into some skia related error:
```
work/revery-quick-start » esy run                                                                                                                                                                  ‹master›
info building reason-skia@github:revery-ui/reason-skia#cc3cfa8@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: reason-skia@github:revery-ui/reason-skia#cc3cfa8
    # esy-build-package: pwd: /Users/rudolfs/.esy/source/i/reason_skia__9732c8be
    # esy-build-package: running: 'refmterr' 'dune' 'build' '-p' 'skia'
        discover src/c_flags.sexp,src/c_library_flags.sexp,src/flags.sexp (exit 2)
    (cd /Users/rudolfs/.esy/3/b/reason_skia-e5245091/default/src && config/discover.exe)
    Fatal error: exception Not_found
        discover src/wrapped/c/c_flags.txt,src/wrapped/c/c_library_flags.txt (exit 2)
    (cd /Users/rudolfs/.esy/3/b/reason_skia-e5245091/default/src/wrapped/c && ../../config/discover.exe)
    Fatal error: exception Not_found
    error: command failed: 'refmterr' 'dune' 'build' '-p' 'skia' (exited with 1)
    esy-build-package: exiting with errors above...

  building reason-skia@github:revery-ui/reason-skia#cc3cfa8
esy: exiting due to errors above
```

I can't verify if the problem still exists at the moment because of this. I'm also not working on Revery stuff at the moment, so I think it's fine if you want to close this issue.

**Comment by glennsl** [comment] 2020-03-18 12:43
Hmm, haven't seen that before. Looks like there might be some environment variable that's not set. If you want to pursue it further I could add some more logging to figure out exactly which, but I'd also try building Revery and reason-skia directly to see if the issue is specifically with the combination of dependencies used for revery-quick-start or if it's more general.

Either way, it's not related to this issue so I'll close this out due to staleness. Feel free to create another issue for the build error if you want to pursue that further, and re-open this or create a new issue for the menubar problem as well if you encounter it in the future.

**Closed as completed by glennsl** 2020-03-18 12:43 UTC
