### ISSUE TITLE
`esy run` results in blank screen on Wayland

### ISSUE THREAD

**Issue by joefiorini** [bryphe/revery-quick-start#51] opened 2020-01-23 17:51 UTC
I'm running ArchLinux with sway 1.2 as my WM. With `SDL_VIDEODRIVER=wayland` I can `esy build` just fine but when I `esy run` I get a blank light blue window:

![image](https://user-images.githubusercontent.com/3648/73009648-f7581380-3dde-11ea-9efb-f35a9d95ee13.png)
However if I run it with `SDL_VIDEODRIVER=x11` I get what I believe is the correct output:

![image](https://user-images.githubusercontent.com/3648/73009710-0e970100-3ddf-11ea-8551-b2846f585db2.png)

SDL is supposed to natively support Wayland. Not sure why this doesn't work, but thought I'd mention it.

**Comment by glennsl** [comment] 2020-03-15 11:02
This should have been fixed in https://github.com/revery-ui/revery/pull/751. I've just updated the quick start to the latest version of Revery, which includes this fix. So if this is still an issue, the issue is most likely upstream and I would recommend testing Revery directly and if it occurs there as well, post an issue on the Revery repo.

**Closed as completed by glennsl** 2020-03-15 11:02 UTC
